# Silver Transform
Test the Silver layer transformation independently.
Note: You should have run bronze_ingestion first so there is pending Bronze data.

In [1]:
import polars as pl
from electricity_maps.layers.silver import transform_silver
from electricity_maps.utils.state import PipelineState
from electricity_maps.config import get_settings

In [2]:
get_settings.cache_clear()
settings = get_settings()
state = PipelineState(settings)

In [3]:
print("Running silver transform...")
result = transform_silver(settings)
print("Silver transformation result:", result)

Running silver transform...
Silver transformation result: {'process_ts': 1777129719141, 'bronze_batches_consumed': 1, 'mix_records': 24, 'flows_records': 173, 'bad_mix_records': 0, 'bad_flows_records': 0}

In [4]:
# Let's inspect the Silver Delta tables
print("Silver Mix Table:")
try:
    path = f"{settings.silver_dir}/electricity_mix"
    df_mix = pl.read_delta(path, storage_options=settings.storage_options)
    display(df_mix.head())
except Exception as e:
    print("Error reading silver mix:", e)

Silver Mix Table:

shape: (5, 25)
┌───────────────┬──────┬────────────────┬────────────────┬───┬────────────────┬──────┬───────┬─────┐
│ process_ts    ┆ zone ┆ datetime       ┆ updated_at     ┆ … ┆ flow_imports_m ┆ year ┆ month ┆ day │
│ ---           ┆ ---  ┆ ---            ┆ ---            ┆   ┆ w              ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ str  ┆ datetime[μs,   ┆ datetime[μs,   ┆   ┆ ---            ┆ i32  ┆ i32   ┆ i32 │
│               ┆      ┆ UTC]           ┆ UTC]           ┆   ┆ f64            ┆      ┆       ┆     │
╞═══════════════╪══════╪════════════════╪════════════════╪═══╪════════════════╪══════╪═══════╪═════╡
│ 1777129719141 ┆ FR   ┆ 2026-04-24     ┆ 2026-04-24     ┆ … ┆ 0.0            ┆ 2026 ┆ 4     ┆ 24  │
│               ┆      ┆ 15:00:00 UTC   ┆ 17:10:58.002   ┆   ┆                ┆      ┆       ┆     │
│               ┆      ┆                ┆ UTC            ┆   ┆                ┆      ┆       ┆     │
│ 1777129719141 ┆ FR   ┆ 2026-04-24     ┆ 2026-04-24     ┆ … ┆ 0.0            ┆ 2026 ┆ 4     ┆ 24  │
│               ┆      ┆ 16:00:00 UTC   ┆ 18:12:55.823   ┆   ┆                ┆      ┆       ┆     │
│               ┆      ┆                ┆ UTC            ┆   ┆                ┆      ┆       ┆     │
│ 1777129719141 ┆ FR   ┆ 2026-04-24     ┆ 2026-04-24     ┆ … ┆ 0.0            ┆ 2026 ┆ 4     ┆ 24  │
│               ┆      ┆ 17:00:00 UTC   ┆ 18:55:00.889   ┆   ┆                ┆      ┆       ┆     │
│               ┆      ┆                ┆ UTC            ┆   ┆                ┆      ┆       ┆     │
│ 1777129719141 ┆ FR   ┆ 2026-04-24     ┆ 2026-04-24     ┆ … ┆ 0.0            ┆ 2026 ┆ 4     ┆ 24  │
│               ┆      ┆ 18:00:00 UTC   ┆ 20:10:10.039   ┆   ┆                ┆      ┆       ┆     │
│               ┆      ┆                ┆ UTC            ┆   ┆                ┆      ┆       ┆     │
│ 1777129719141 ┆ FR   ┆ 2026-04-24     ┆ 2026-04-24     ┆ … ┆ 0.0            ┆ 2026 ┆ 4     ┆ 24  │
│               ┆      ┆ 19:00:00 UTC   ┆ 21:24:54.199   ┆   ┆                ┆      ┆       ┆     │
│               ┆      ┆                ┆ UTC            ┆   ┆                ┆      ┆       ┆     │
└───────────────┴──────┴────────────────┴────────────────┴───┴────────────────┴──────┴───────┴─────┘

In [5]:
print("\nSilver Flows Table:")
try:
    path = f"{settings.silver_dir}/electricity_flows"
    df_flows = pl.read_delta(path, storage_options=settings.storage_options)
    display(df_flows.head())
except Exception as e:
    print("Error reading silver flows:", e)

Silver Flows Table:

shape: (5, 10)
┌───────────────┬──────┬───────────────────┬───────────────────┬───┬──────────┬──────┬───────┬─────┐
│ process_ts    ┆ zone ┆ datetime          ┆ updated_at        ┆ … ┆ power_mw ┆ year ┆ month ┆ day │
│ ---           ┆ ---  ┆ ---               ┆ ---               ┆   ┆ ---      ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ str  ┆ datetime[μs, UTC] ┆ datetime[μs, UTC] ┆   ┆ f64      ┆ i32  ┆ i32   ┆ i32 │
╞═══════════════╪══════╪═══════════════════╪═══════════════════╪═══╪══════════╪══════╪═══════╪═════╡
│ 1777129719141 ┆ FR   ┆ 2026-04-24        ┆ 2026-04-24        ┆ … ┆ 2788.0   ┆ 2026 ┆ 4     ┆ 24  │
│               ┆      ┆ 15:00:00 UTC      ┆ 17:10:58.002 UTC  ┆   ┆          ┆      ┆       ┆     │
│ 1777129719141 ┆ FR   ┆ 2026-04-24        ┆ 2026-04-24        ┆ … ┆ 2395.0   ┆ 2026 ┆ 4     ┆ 24  │
│               ┆      ┆ 15:00:00 UTC      ┆ 17:10:58.002 UTC  ┆   ┆          ┆      ┆       ┆     │
│ 1777129719141 ┆ FR   ┆ 2026-04-24        ┆ 2026-04-24        ┆ … ┆ 1683.0   ┆ 2026 ┆ 4     ┆ 24  │
│               ┆      ┆ 15:00:00 UTC      ┆ 17:10:58.002 UTC  ┆   ┆          ┆      ┆       ┆     │
│ 1777129719141 ┆ FR   ┆ 2026-04-24        ┆ 2026-04-24        ┆ … ┆ 2543.0   ┆ 2026 ┆ 4     ┆ 24  │
│               ┆      ┆ 15:00:00 UTC      ┆ 17:10:58.002 UTC  ┆   ┆          ┆      ┆       ┆     │
│ 1777129719141 ┆ FR   ┆ 2026-04-24        ┆ 2026-04-24        ┆ … ┆ 3015.0   ┆ 2026 ┆ 4     ┆ 24  │
│               ┆      ┆ 15:00:00 UTC      ┆ 17:10:58.002 UTC  ┆   ┆          ┆      ┆       ┆     │
└───────────────┴──────┴───────────────────┴───────────────────┴───┴──────────┴──────┴───────┴─────┘