# Silver Transform
Test the Silver layer transformation independently.
Note: You should have run bronze_ingestion first so there is pending Bronze data.

In [1]:
from datetime import datetime, timezone
import polars as pl
from electricity_maps.layers.silver import transform_silver_flows, transform_silver_mix
from electricity_maps.utils.state import PipelineState
from electricity_maps.utils.storage import delta_storage_options
from electricity_maps.config import get_settings

In [2]:
get_settings.cache_clear()
settings = get_settings()
state = PipelineState(settings.data_dir)

now = datetime.now(timezone.utc)
silver_ts = int(now.timestamp())

In [3]:
ts_list = state.pickup_ready("bronze")
if not ts_list:
    print("No pending bronze data found. Run 02_bronze_ingestion first.")
else:
    print(f"Picked up Bronze batches: {ts_list}")
    
    transform_silver_mix(ts_list)
    transform_silver_flows(ts_list)
    
    # Mark state
    state.mark_complete("bronze", ts_list)
    state.init_layer("silver", silver_ts, now)
    state.mark_ready("silver", silver_ts, now, len(ts_list))
    
    print("Silver transformation completed!")

2026-04-25T08:39:01.247913Z [info     ] el_state: no ready rows to pick up [electricity_maps.utils.state] process=bronze
No pending bronze data found. Run 02_bronze_ingestion first.

In [4]:
# Let's inspect the Silver Delta tables
print("Silver Mix Table:")
try:
    path = str(settings.silver_dir / "electricity_mix")
    df_mix = pl.read_delta(path, storage_options=delta_storage_options(path))
    display(df_mix.head())
except Exception as e:
    print("Error reading silver mix:", e)

Silver Mix Table:

shape: (5, 24)
┌──────┬─────────────────┬────────────────┬──────────────┬───┬────────────────┬──────┬───────┬─────┐
│ zone ┆ datetime        ┆ updated_at     ┆ is_estimated ┆ … ┆ flow_imports_m ┆ year ┆ month ┆ day │
│ ---  ┆ ---             ┆ ---            ┆ ---          ┆   ┆ w              ┆ ---  ┆ ---   ┆ --- │
│ str  ┆ datetime[μs,    ┆ datetime[μs,   ┆ bool         ┆   ┆ ---            ┆ i32  ┆ i32   ┆ i32 │
│      ┆ UTC]            ┆ UTC]           ┆              ┆   ┆ f64            ┆      ┆       ┆     │
╞══════╪═════════════════╪════════════════╪══════════════╪═══╪════════════════╪══════╪═══════╪═════╡
│ FR   ┆ 2026-04-25      ┆ 2026-04-25     ┆ true         ┆ … ┆ 0.0            ┆ 2026 ┆ 4     ┆ 25  │
│      ┆ 06:00:00 UTC    ┆ 08:09:01.663   ┆              ┆   ┆                ┆      ┆       ┆     │
│      ┆                 ┆ UTC            ┆              ┆   ┆                ┆      ┆       ┆     │
│ FR   ┆ 2026-04-25      ┆ 2026-04-25     ┆ true         ┆ … ┆ 0.0            ┆ 2026 ┆ 4     ┆ 25  │
│      ┆ 01:00:00 UTC    ┆ 03:08:12.543   ┆              ┆   ┆                ┆      ┆       ┆     │
│      ┆                 ┆ UTC            ┆              ┆   ┆                ┆      ┆       ┆     │
│ FR   ┆ 2026-04-25      ┆ 2026-04-25     ┆ true         ┆ … ┆ 0.0            ┆ 2026 ┆ 4     ┆ 25  │
│      ┆ 03:00:00 UTC    ┆ 05:23:17.793   ┆              ┆   ┆                ┆      ┆       ┆     │
│      ┆                 ┆ UTC            ┆              ┆   ┆                ┆      ┆       ┆     │
│ FR   ┆ 2026-04-25      ┆ 2026-04-25     ┆ true         ┆ … ┆ 0.0            ┆ 2026 ┆ 4     ┆ 25  │
│      ┆ 02:00:00 UTC    ┆ 04:23:38.601   ┆              ┆   ┆                ┆      ┆       ┆     │
│      ┆                 ┆ UTC            ┆              ┆   ┆                ┆      ┆       ┆     │
│ FR   ┆ 2026-04-25      ┆ 2026-04-25     ┆ true         ┆ … ┆ 0.0            ┆ 2026 ┆ 4     ┆ 25  │
│      ┆ 07:00:00 UTC    ┆ 08:08:49.055   ┆              ┆   ┆                ┆      ┆       ┆     │
│      ┆                 ┆ UTC            ┆              ┆   ┆                ┆      ┆       ┆     │
└──────┴─────────────────┴────────────────┴──────────────┴───┴────────────────┴──────┴───────┴─────┘

In [5]:
print("\nSilver Flows Table:")
try:
    path = str(settings.silver_dir / "electricity_flows")
    df_flows = pl.read_delta(path, storage_options=delta_storage_options(path))
    display(df_flows.head())
except Exception as e:
    print("Error reading silver flows:", e)

Silver Flows Table:

shape: (5, 9)
┌──────┬───────────────────┬───────────────────┬───────────────┬───┬──────────┬──────┬───────┬─────┐
│ zone ┆ datetime          ┆ updated_at        ┆ neighbor_zone ┆ … ┆ power_mw ┆ year ┆ month ┆ day │
│ ---  ┆ ---               ┆ ---               ┆ ---           ┆   ┆ ---      ┆ ---  ┆ ---   ┆ --- │
│ str  ┆ datetime[μs, UTC] ┆ datetime[μs, UTC] ┆ str           ┆   ┆ f64      ┆ i32  ┆ i32   ┆ i32 │
╞══════╪═══════════════════╪═══════════════════╪═══════════════╪═══╪══════════╪══════╪═══════╪═════╡
│ FR   ┆ 2026-04-25        ┆ 2026-04-25        ┆ GB            ┆ … ┆ 2247.0   ┆ 2026 ┆ 4     ┆ 25  │
│      ┆ 03:00:00 UTC      ┆ 05:23:17.793 UTC  ┆               ┆   ┆          ┆      ┆       ┆     │
│ FR   ┆ 2026-04-25        ┆ 2026-04-25        ┆ CH            ┆ … ┆ 1815.0   ┆ 2026 ┆ 4     ┆ 25  │
│      ┆ 01:00:00 UTC      ┆ 03:08:12.543 UTC  ┆               ┆   ┆          ┆      ┆       ┆     │
│ FR   ┆ 2026-04-25        ┆ 2026-04-25        ┆ LU            ┆ … ┆ 144.0    ┆ 2026 ┆ 4     ┆ 25  │
│      ┆ 05:00:00 UTC      ┆ 07:10:34.382 UTC  ┆               ┆   ┆          ┆      ┆       ┆     │
│ FR   ┆ 2026-04-25        ┆ 2026-04-25        ┆ LU            ┆ … ┆ 248.0    ┆ 2026 ┆ 4     ┆ 25  │
│      ┆ 03:00:00 UTC      ┆ 05:23:17.793 UTC  ┆               ┆   ┆          ┆      ┆       ┆     │
│ FR   ┆ 2026-04-25        ┆ 2026-04-25        ┆ ES            ┆ … ┆ 2555.0   ┆ 2026 ┆ 4     ┆ 25  │
│      ┆ 04:00:00 UTC      ┆ 06:24:03.931 UTC  ┆               ┆   ┆          ┆      ┆       ┆     │
└──────┴───────────────────┴───────────────────┴───────────────┴───┴──────────┴──────┴───────┴─────┘