# Gold Aggregation
Test the Gold layer aggregations independently.
Note: You should have run silver_transform first so there is pending Silver data.

In [1]:
import polars as pl

from electricity_maps.config import get_settings
from electricity_maps.layers.gold import transform_gold
from electricity_maps.utils.state import PipelineState

In [2]:
get_settings.cache_clear()
settings = get_settings()
state = PipelineState(settings)

In [3]:
print("Running gold aggregation...")
result = transform_gold(settings)
print("Gold transformation result:", result)

Running gold aggregation...

2026-04-26 22:36:49,608 - electricity_maps.layers.gold - INFO - gold_started: process_ts=1777223204564, silver_batches=1
2026-04-26 22:36:53,968 - electricity_maps.layers.gold - INFO - gold_aggregated: mix_records=1, imports_records=4, exports_records=3
2026-04-26 22:37:05,376 - electricity_maps.layers.gold - INFO - gold_completed: mix_records=1, imports_records=4, exports_records=3

Gold transformation result: {'process_ts': 1777223204564, 'silver_batches_consumed': 1, 'mix_records': 1, 'imports_records': 4, 'exports_records': 3}

In [4]:
# Inspect Gold Mix Summary
print("Gold Daily Mix Summary:")
try:
    path = f"{settings.gold_dir}/daily_electricity_mix"
    df_gold_mix = pl.read_delta(path, storage_options=settings.storage_options)
    display(df_gold_mix.head())
except Exception as e:
    print("Error reading gold mix:", e)

Gold Daily Mix Summary:

shape: (2, 21)
┌───────────────┬──────┬───────────┬────────────┬───┬───────────────┬──────┬───────┬─────┐
│ process_ts    ┆ zone ┆ zone_name ┆ date       ┆ … ┆ hours_covered ┆ year ┆ month ┆ day │
│ ---           ┆ ---  ┆ ---       ┆ ---        ┆   ┆ ---           ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ str  ┆ str       ┆ date       ┆   ┆ i32           ┆ i32  ┆ i32   ┆ i32 │
╞═══════════════╪══════╪═══════════╪════════════╪═══╪═══════════════╪══════╪═══════╪═════╡
│ 1777223204564 ┆ FR   ┆ France    ┆ 2026-04-26 ┆ … ┆ 17            ┆ 2026 ┆ 4     ┆ 26  │
│ 1777205541513 ┆ FR   ┆ France    ┆ 2026-04-25 ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
└───────────────┴──────┴───────────┴────────────┴───┴───────────────┴──────┴───────┴─────┘

In [5]:
# Inspect Gold Daily Imports
print("\nGold Daily Imports:")
try:
    path = f"{settings.gold_dir}/daily_imports"
    df_imports = pl.read_delta(path, storage_options=settings.storage_options)
    display(df_imports.head())
except Exception as e:
    print("Error reading gold imports:", e)

Gold Daily Imports:

shape: (5, 11)
┌───────────────┬──────┬───────────┬─────────────┬───┬───────────────┬──────┬───────┬─────┐
│ process_ts    ┆ zone ┆ zone_name ┆ source_zone ┆ … ┆ hours_covered ┆ year ┆ month ┆ day │
│ ---           ┆ ---  ┆ ---       ┆ ---         ┆   ┆ ---           ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ str  ┆ str       ┆ str         ┆   ┆ i32           ┆ i32  ┆ i32   ┆ i32 │
╞═══════════════╪══════╪═══════════╪═════════════╪═══╪═══════════════╪══════╪═══════╪═════╡
│ 1777205541513 ┆ FR   ┆ France    ┆ ES          ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777205541513 ┆ FR   ┆ France    ┆ CH          ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777205541513 ┆ FR   ┆ France    ┆ DE          ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777205541513 ┆ FR   ┆ France    ┆ BE          ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777223204564 ┆ FR   ┆ France    ┆ DE          ┆ … ┆ 17            ┆ 2026 ┆ 4     ┆ 26  │
└───────────────┴──────┴───────────┴─────────────┴───┴───────────────┴──────┴───────┴─────┘