# Gold Aggregation
Test the Gold layer aggregations independently.
Note: You should have run silver_transform first so there is pending Silver data.

In [1]:
import polars as pl
from electricity_maps.layers.gold import transform_gold
from electricity_maps.utils.state import PipelineState
from electricity_maps.config import get_settings

In [2]:
get_settings.cache_clear()
settings = get_settings()
state = PipelineState(settings)

In [3]:
print("Running gold aggregation...")
result = transform_gold(settings)
print("Gold transformation result:", result)

Running gold aggregation...
Gold transformation result: {'process_ts': 1777129788867, 'silver_batches_consumed': 1, 'mix_records': 2, 'imports_records': 8, 'exports_records': 6}

In [4]:
# Inspect Gold Mix Summary
print("Gold Daily Mix Summary:")
try:
    path = f"{settings.gold_dir}/daily_electricity_mix"
    df_gold_mix = pl.read_delta(path, storage_options=settings.storage_options)
    display(df_gold_mix.head())
except Exception as e:
    print("Error reading gold mix:", e)

Gold Daily Mix Summary:

shape: (2, 21)
┌───────────────┬──────┬───────────┬────────────┬───┬───────────────┬──────┬───────┬─────┐
│ process_ts    ┆ zone ┆ zone_name ┆ date       ┆ … ┆ hours_covered ┆ year ┆ month ┆ day │
│ ---           ┆ ---  ┆ ---       ┆ ---        ┆   ┆ ---           ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ str  ┆ str       ┆ date       ┆   ┆ i32           ┆ i32  ┆ i32   ┆ i32 │
╞═══════════════╪══════╪═══════════╪════════════╪═══╪═══════════════╪══════╪═══════╪═════╡
│ 1777129788867 ┆ FR   ┆ France    ┆ 2026-04-24 ┆ … ┆ 9             ┆ 2026 ┆ 4     ┆ 24  │
│ 1777129788867 ┆ FR   ┆ France    ┆ 2026-04-25 ┆ … ┆ 15            ┆ 2026 ┆ 4     ┆ 25  │
└───────────────┴──────┴───────────┴────────────┴───┴───────────────┴──────┴───────┴─────┘

In [5]:
# Inspect Gold Daily Imports
print("\nGold Daily Imports:")
try:
    path = f"{settings.gold_dir}/daily_imports"
    df_imports = pl.read_delta(path, storage_options=settings.storage_options)
    display(df_imports.head())
except Exception as e:
    print("Error reading gold imports:", e)

Gold Daily Imports:

shape: (5, 11)
┌───────────────┬──────┬───────────┬─────────────┬───┬───────────────┬──────┬───────┬─────┐
│ process_ts    ┆ zone ┆ zone_name ┆ source_zone ┆ … ┆ hours_covered ┆ year ┆ month ┆ day │
│ ---           ┆ ---  ┆ ---       ┆ ---         ┆   ┆ ---           ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ str  ┆ str       ┆ str         ┆   ┆ i32           ┆ i32  ┆ i32   ┆ i32 │
╞═══════════════╪══════╪═══════════╪═════════════╪═══╪═══════════════╪══════╪═══════╪═════╡
│ 1777129788867 ┆ FR   ┆ France    ┆ DE          ┆ … ┆ 15            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777129788867 ┆ FR   ┆ France    ┆ ES          ┆ … ┆ 15            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777129788867 ┆ FR   ┆ France    ┆ CH          ┆ … ┆ 15            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777129788867 ┆ FR   ┆ France    ┆ BE          ┆ … ┆ 15            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777129788867 ┆ FR   ┆ France    ┆ BE          ┆ … ┆ 9             ┆ 2026 ┆ 4     ┆ 24  │
└───────────────┴──────┴───────────┴─────────────┴───┴───────────────┴──────┴───────┴─────┘