# Delta table Query util
This notebook uses **Polars SQL** to query the Delta tables in the Delta lake tables from S3. 

It maintains compatibility with the original SQL syntax by automatically resolving `schema.table` references to the correct S3 Delta paths.

In [1]:
import os
import re

import certifi
import polars as pl

from electricity_maps.config import get_settings

os.environ["AWS_CA_BUNDLE"] = certifi.where()
os.environ["SSL_CERT_FILE"] = certifi.where()

get_settings.cache_clear()
settings = get_settings()
DATA_DIR = settings.data_dir
so = settings.storage_options

In [2]:
def get_sql_df(sql_query):
    """Execute SQL query using Polars SQLContext."""
    ctx = pl.SQLContext()

    # 1. Identify all 'schema.table' references (e.g. bronze.electricity_flows)
    table_refs = re.findall(r'([a-zA-Z0-9_]+\.[a-zA-Z0-9_]+)', sql_query)

    # 2. Register each table in the context and prepare a version of the SQL
    # that Polars' parser can handle (identifiers with dots usually need quoting)
    working_sql = sql_query
    for ref in set(table_refs):
        schema, table = ref.split('.')
        path = f"{DATA_DIR}/{schema}/{table}"

        try:
            # Use scan_delta for efficient lazy execution
            lf = pl.scan_delta(path, storage_options=so)

            # Register the table. We use a safe alias (no dots) for the internal registration
            # to avoid namespace parsing issues in Polars SQL.
            safe_alias = f"{schema}_{table}"
            ctx.register(safe_alias, lf)

            # Replace the original 'schema.table' with the 'safe_alias' in the working SQL
            working_sql = working_sql.replace(ref, safe_alias)

        except Exception as e:
            print(f"Warning: Could not load table {ref} from {path}: {e}")

    # 3. Execute the modified SQL and collect results
    return ctx.execute(working_sql).collect()

def print_sql_df(sql_query, label=None):
    """Helper to display the result of a SQL query."""
    if label:
        print(f"\n{label}:")
    return get_sql_df(sql_query)

In [11]:
print_sql_df('select * from bronze.electricity_flows order by process_ts desc limit 10', "Bronze Daily Flows Summary")

Bronze Daily Flows Summary:

shape: (2, 11)
┌───────────────┬─────────────────┬─────────────────┬──────┬───┬──────────────┬──────┬───────┬─────┐
│ process_ts    ┆ ingestion_times ┆ source_url      ┆ zone ┆ … ┆ record_count ┆ year ┆ month ┆ day │
│ ---           ┆ tamp            ┆ ---             ┆ ---  ┆   ┆ ---          ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ ---             ┆ str             ┆ str  ┆   ┆ i64          ┆ i64  ┆ i64   ┆ i64 │
│               ┆ datetime[μs,    ┆                 ┆      ┆   ┆              ┆      ┆       ┆     │
│               ┆ UTC]            ┆                 ┆      ┆   ┆              ┆      ┆       ┆     │
╞═══════════════╪═════════════════╪═════════════════╪══════╪═══╪══════════════╪══════╪═══════╪═════╡
│ 1777301860571 ┆ 2026-04-27      ┆ https://api.ele ┆ FR   ┆ … ┆ 1            ┆ 2026 ┆ 4     ┆ 27  │
│               ┆ 14:57:40.571618 ┆ ctricitymaps.co ┆      ┆   ┆              ┆      ┆       ┆     │
│               ┆ UTC             ┆ …               ┆      ┆   ┆              ┆      ┆       ┆     │
│ 1777223123493 ┆ 2026-04-26      ┆ https://api.ele ┆ FR   ┆ … ┆ 4            ┆ 2026 ┆ 4     ┆ 26  │
│               ┆ 17:05:23.493984 ┆ ctricitymaps.co ┆      ┆   ┆              ┆      ┆       ┆     │
│               ┆ UTC             ┆ …               ┆      ┆   ┆              ┆      ┆       ┆     │
└───────────────┴─────────────────┴─────────────────┴──────┴───┴──────────────┴──────┴───────┴─────┘

In [12]:
print_sql_df('select * from bronze.electricity_mix order by process_ts desc limit 10', "Bronze Daily Mix Summary")

Bronze Daily Mix Summary:

shape: (2, 11)
┌───────────────┬─────────────────┬─────────────────┬──────┬───┬──────────────┬──────┬───────┬─────┐
│ process_ts    ┆ ingestion_times ┆ source_url      ┆ zone ┆ … ┆ record_count ┆ year ┆ month ┆ day │
│ ---           ┆ tamp            ┆ ---             ┆ ---  ┆   ┆ ---          ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ ---             ┆ str             ┆ str  ┆   ┆ i64          ┆ i64  ┆ i64   ┆ i64 │
│               ┆ datetime[μs,    ┆                 ┆      ┆   ┆              ┆      ┆       ┆     │
│               ┆ UTC]            ┆                 ┆      ┆   ┆              ┆      ┆       ┆     │
╞═══════════════╪═════════════════╪═════════════════╪══════╪═══╪══════════════╪══════╪═══════╪═════╡
│ 1777301860571 ┆ 2026-04-27      ┆ https://api.ele ┆ FR   ┆ … ┆ 1            ┆ 2026 ┆ 4     ┆ 27  │
│               ┆ 14:57:40.571618 ┆ ctricitymaps.co ┆      ┆   ┆              ┆      ┆       ┆     │
│               ┆ UTC             ┆ …               ┆      ┆   ┆              ┆      ┆       ┆     │
│ 1777223123493 ┆ 2026-04-26      ┆ https://api.ele ┆ FR   ┆ … ┆ 4            ┆ 2026 ┆ 4     ┆ 26  │
│               ┆ 17:05:23.493984 ┆ ctricitymaps.co ┆      ┆   ┆              ┆      ┆       ┆     │
│               ┆ UTC             ┆ …               ┆      ┆   ┆              ┆      ┆       ┆     │
└───────────────┴─────────────────┴─────────────────┴──────┴───┴──────────────┴──────┴───────┴─────┘

In [5]:
print_sql_df('select * from silver.electricity_mix order by process_ts desc limit 6', "Silver Mix")

Silver Mix:

shape: (6, 25)
┌───────────────┬──────┬────────────────┬────────────────┬───┬────────────────┬──────┬───────┬─────┐
│ process_ts    ┆ zone ┆ datetime       ┆ updated_at     ┆ … ┆ flow_imports_m ┆ year ┆ month ┆ day │
│ ---           ┆ ---  ┆ ---            ┆ ---            ┆   ┆ w              ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ str  ┆ datetime[μs]   ┆ datetime[μs]   ┆   ┆ ---            ┆ i32  ┆ i32   ┆ i32 │
│               ┆      ┆                ┆                ┆   ┆ f64            ┆      ┆       ┆     │
╞═══════════════╪══════╪════════════════╪════════════════╪═══╪════════════════╪══════╪═══════╪═════╡
│ 1777223153884 ┆ FR   ┆ 2026-04-26     ┆ 2026-04-26     ┆ … ┆ 100.0          ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 13:00:00       ┆ 16:10:07.341   ┆   ┆                ┆      ┆       ┆     │
│ 1777223153884 ┆ FR   ┆ 2026-04-26     ┆ 2026-04-26     ┆ … ┆ 0.0            ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 14:00:00       ┆ 16:10:07.341   ┆   ┆                ┆      ┆       ┆     │
│ 1777223153884 ┆ FR   ┆ 2026-04-26     ┆ 2026-04-26     ┆ … ┆ 242.0          ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 15:00:00       ┆ 16:39:27.255   ┆   ┆                ┆      ┆       ┆     │
│ 1777223153884 ┆ FR   ┆ 2026-04-26     ┆ 2026-04-26     ┆ … ┆ 0.0            ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 16:00:00       ┆ 16:39:27.255   ┆   ┆                ┆      ┆       ┆     │
│ 1777212885259 ┆ FR   ┆ 2026-04-26     ┆ 2026-04-26     ┆ … ┆ 570.0          ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 12:00:00       ┆ 13:55:18.001   ┆   ┆                ┆      ┆       ┆     │
│ 1777206207772 ┆ FR   ┆ 2026-04-26     ┆ 2026-04-26     ┆ … ┆ 1082.0         ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 11:00:00       ┆ 11:54:21.220   ┆   ┆                ┆      ┆       ┆     │
└───────────────┴──────┴────────────────┴────────────────┴───┴────────────────┴──────┴───────┴─────┘

In [6]:
print_sql_df('select * from silver.electricity_flows order by process_ts desc limit 10', "Silver Flows")

Silver Flows:

shape: (10, 10)
┌───────────────┬──────┬───────────────┬───────────────┬───┬──────────┬──────┬───────┬─────┐
│ process_ts    ┆ zone ┆ datetime      ┆ updated_at    ┆ … ┆ power_mw ┆ year ┆ month ┆ day │
│ ---           ┆ ---  ┆ ---           ┆ ---           ┆   ┆ ---      ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ str  ┆ datetime[μs]  ┆ datetime[μs]  ┆   ┆ f64      ┆ i32  ┆ i32   ┆ i32 │
╞═══════════════╪══════╪═══════════════╪═══════════════╪═══╪══════════╪══════╪═══════╪═════╡
│ 1777223153884 ┆ FR   ┆ 2026-04-26    ┆ 2026-04-26    ┆ … ┆ 2365.0   ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 13:00:00      ┆ 16:10:07.341  ┆   ┆          ┆      ┆       ┆     │
│ 1777223153884 ┆ FR   ┆ 2026-04-26    ┆ 2026-04-26    ┆ … ┆ 1028.0   ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 13:00:00      ┆ 16:10:07.341  ┆   ┆          ┆      ┆       ┆     │
│ 1777223153884 ┆ FR   ┆ 2026-04-26    ┆ 2026-04-26    ┆ … ┆ 2666.0   ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 13:00:00      ┆ 16:10:07.341  ┆   ┆          ┆      ┆       ┆     │
│ 1777223153884 ┆ FR   ┆ 2026-04-26    ┆ 2026-04-26    ┆ … ┆ 3016.0   ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 13:00:00      ┆ 16:10:07.341  ┆   ┆          ┆      ┆       ┆     │
│ 1777223153884 ┆ FR   ┆ 2026-04-26    ┆ 2026-04-26    ┆ … ┆ 180.0    ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 13:00:00      ┆ 16:10:07.341  ┆   ┆          ┆      ┆       ┆     │
│ 1777223153884 ┆ FR   ┆ 2026-04-26    ┆ 2026-04-26    ┆ … ┆ 127.0    ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 13:00:00      ┆ 16:10:07.341  ┆   ┆          ┆      ┆       ┆     │
│ 1777223153884 ┆ FR   ┆ 2026-04-26    ┆ 2026-04-26    ┆ … ┆ 2044.0   ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 14:00:00      ┆ 16:10:07.341  ┆   ┆          ┆      ┆       ┆     │
│ 1777223153884 ┆ FR   ┆ 2026-04-26    ┆ 2026-04-26    ┆ … ┆ 602.0    ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 14:00:00      ┆ 16:10:07.341  ┆   ┆          ┆      ┆       ┆     │
│ 1777223153884 ┆ FR   ┆ 2026-04-26    ┆ 2026-04-26    ┆ … ┆ 1691.0   ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 14:00:00      ┆ 16:10:07.341  ┆   ┆          ┆      ┆       ┆     │
│ 1777223153884 ┆ FR   ┆ 2026-04-26    ┆ 2026-04-26    ┆ … ┆ 1848.0   ┆ 2026 ┆ 4     ┆ 26  │
│               ┆      ┆ 14:00:00      ┆ 16:10:07.341  ┆   ┆          ┆      ┆       ┆     │
└───────────────┴──────┴───────────────┴───────────────┴───┴──────────┴──────┴───────┴─────┘

In [7]:
print_sql_df('select * from gold.daily_exports order by process_ts desc limit 10', "Gold Daily Exports")

Gold Daily Exports:

shape: (6, 11)
┌───────────────┬──────┬───────────┬──────────────────┬───┬───────────────┬──────┬───────┬─────┐
│ process_ts    ┆ zone ┆ zone_name ┆ destination_zone ┆ … ┆ hours_covered ┆ year ┆ month ┆ day │
│ ---           ┆ ---  ┆ ---       ┆ ---              ┆   ┆ ---           ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ str  ┆ str       ┆ str              ┆   ┆ i32           ┆ i32  ┆ i32   ┆ i32 │
╞═══════════════╪══════╪═══════════╪══════════════════╪═══╪═══════════════╪══════╪═══════╪═════╡
│ 1777223204564 ┆ FR   ┆ France    ┆ GB               ┆ … ┆ 17            ┆ 2026 ┆ 4     ┆ 26  │
│ 1777223204564 ┆ FR   ┆ France    ┆ LU               ┆ … ┆ 17            ┆ 2026 ┆ 4     ┆ 26  │
│ 1777223204564 ┆ FR   ┆ France    ┆ IT-NO            ┆ … ┆ 17            ┆ 2026 ┆ 4     ┆ 26  │
│ 1777205541513 ┆ FR   ┆ France    ┆ IT-NO            ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777205541513 ┆ FR   ┆ France    ┆ GB               ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777205541513 ┆ FR   ┆ France    ┆ LU               ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
└───────────────┴──────┴───────────┴──────────────────┴───┴───────────────┴──────┴───────┴─────┘

In [8]:
print_sql_df('SELECT * FROM gold.daily_imports order by process_ts desc LIMIT 10', "Gold Daily Imports")

Gold Daily Imports:

shape: (8, 11)
┌───────────────┬──────┬───────────┬─────────────┬───┬───────────────┬──────┬───────┬─────┐
│ process_ts    ┆ zone ┆ zone_name ┆ source_zone ┆ … ┆ hours_covered ┆ year ┆ month ┆ day │
│ ---           ┆ ---  ┆ ---       ┆ ---         ┆   ┆ ---           ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ str  ┆ str       ┆ str         ┆   ┆ i32           ┆ i32  ┆ i32   ┆ i32 │
╞═══════════════╪══════╪═══════════╪═════════════╪═══╪═══════════════╪══════╪═══════╪═════╡
│ 1777223204564 ┆ FR   ┆ France    ┆ DE          ┆ … ┆ 17            ┆ 2026 ┆ 4     ┆ 26  │
│ 1777223204564 ┆ FR   ┆ France    ┆ ES          ┆ … ┆ 17            ┆ 2026 ┆ 4     ┆ 26  │
│ 1777223204564 ┆ FR   ┆ France    ┆ CH          ┆ … ┆ 16            ┆ 2026 ┆ 4     ┆ 26  │
│ 1777223204564 ┆ FR   ┆ France    ┆ BE          ┆ … ┆ 17            ┆ 2026 ┆ 4     ┆ 26  │
│ 1777205541513 ┆ FR   ┆ France    ┆ ES          ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777205541513 ┆ FR   ┆ France    ┆ CH          ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777205541513 ┆ FR   ┆ France    ┆ DE          ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
│ 1777205541513 ┆ FR   ┆ France    ┆ BE          ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
└───────────────┴──────┴───────────┴─────────────┴───┴───────────────┴──────┴───────┴─────┘

In [9]:
print_sql_df('SELECT * FROM gold.daily_electricity_mix order by process_ts desc LIMIT 10', "Gold Daily Mix")

Gold Daily Mix:

shape: (2, 21)
┌───────────────┬──────┬───────────┬────────────┬───┬───────────────┬──────┬───────┬─────┐
│ process_ts    ┆ zone ┆ zone_name ┆ date       ┆ … ┆ hours_covered ┆ year ┆ month ┆ day │
│ ---           ┆ ---  ┆ ---       ┆ ---        ┆   ┆ ---           ┆ ---  ┆ ---   ┆ --- │
│ i64           ┆ str  ┆ str       ┆ date       ┆   ┆ i32           ┆ i32  ┆ i32   ┆ i32 │
╞═══════════════╪══════╪═══════════╪════════════╪═══╪═══════════════╪══════╪═══════╪═════╡
│ 1777223204564 ┆ FR   ┆ France    ┆ 2026-04-26 ┆ … ┆ 17            ┆ 2026 ┆ 4     ┆ 26  │
│ 1777205541513 ┆ FR   ┆ France    ┆ 2026-04-25 ┆ … ┆ 12            ┆ 2026 ┆ 4     ┆ 25  │
└───────────────┴──────┴───────────┴────────────┴───┴───────────────┴──────┴───────┴─────┘

In [10]:
print_sql_df('SELECT * FROM state.el_state ORDER BY process_ts DESC limit 10', "Pipeline State (el_state)")

Pipeline State (el_state):

shape: (10, 7)
┌─────────┬───────────────┬────────────────┬───────────────┬────────┬──────────────┬───────────────┐
│ process ┆ process_ts    ┆ start_timestam ┆ end_timestamp ┆ status ┆ record_count ┆ error_message │
│ ---     ┆ ---           ┆ p              ┆ ---           ┆ ---    ┆ ---          ┆ ---           │
│ str     ┆ i64           ┆ ---            ┆ datetime[μs,  ┆ str    ┆ i64          ┆ str           │
│         ┆               ┆ datetime[μs,   ┆ UTC]          ┆        ┆              ┆               │
│         ┆               ┆ UTC]           ┆               ┆        ┆              ┆               │
╞═════════╪═══════════════╪════════════════╪═══════════════╪════════╪══════════════╪═══════════════╡
│ gold    ┆ 1777223204564 ┆ 2026-04-26 17: ┆ 2026-04-26    ┆ R      ┆ 8            ┆ null          │
│         ┆               ┆ 06:49.610194   ┆ 17:07:01.8546 ┆        ┆              ┆               │
│         ┆               ┆ UTC            ┆ 72 UTC        ┆        ┆              ┆               │
│ silver  ┆ 1777223153884 ┆ 2026-04-26 17: ┆ 2026-04-26    ┆ C      ┆ 32           ┆ null          │
│         ┆               ┆ 06:06.581631   ┆ 17:06:28.6400 ┆        ┆              ┆               │
│         ┆               ┆ UTC            ┆ 11 UTC        ┆        ┆              ┆               │
│ bronze  ┆ 1777223123493 ┆ 2026-04-26 17: ┆ 2026-04-26    ┆ C      ┆ 8            ┆ null          │
│         ┆               ┆ 05:23.493984   ┆ 17:05:36.1790 ┆        ┆              ┆               │
│         ┆               ┆ UTC            ┆ 15 UTC        ┆        ┆              ┆               │
│ bronze  ┆ 1777220910307 ┆ 2026-04-26 16: ┆ 2026-04-26    ┆ C      ┆ 2            ┆ null          │
│         ┆               ┆ 28:30.307016   ┆ 16:28:34.7636 ┆        ┆              ┆               │
│         ┆               ┆ UTC            ┆ 17 UTC        ┆        ┆              ┆               │
│ bronze  ┆ 1777220841657 ┆ 2026-04-26 16: ┆ 2026-04-26    ┆ C      ┆ 2            ┆ null          │
│         ┆               ┆ 27:21.657825   ┆ 16:27:25.0210 ┆        ┆              ┆               │
│         ┆               ┆ UTC            ┆ 86 UTC        ┆        ┆              ┆               │
│ bronze  ┆ 1777220785217 ┆ 2026-04-26 16: ┆ 2026-04-26    ┆ C      ┆ 2            ┆ null          │
│         ┆               ┆ 26:25.217956   ┆ 16:26:30.0349 ┆        ┆              ┆               │
│         ┆               ┆ UTC            ┆ 57 UTC        ┆        ┆              ┆               │
│ bronze  ┆ 1777220614789 ┆ 2026-04-26 16: ┆ 2026-04-26    ┆ C      ┆ 2            ┆ null          │
│         ┆               ┆ 23:34.789398   ┆ 16:23:39.2208 ┆        ┆              ┆               │
│         ┆               ┆ UTC            ┆ 70 UTC        ┆        ┆              ┆               │
│ gold    ┆ 1777216802197 ┆ 2026-04-26 15: ┆ 2026-04-26    ┆ R      ┆ 8            ┆ null          │
│         ┆               ┆ 20:06.957933   ┆ 15:20:19.5646 ┆        ┆              ┆               │
│         ┆               ┆ UTC            ┆ 35 UTC        ┆        ┆              ┆               │
│ silver  ┆ 1777216202290 ┆ 2026-04-26 15: ┆ 2026-04-26    ┆ C      ┆ 16           ┆ null          │
│         ┆               ┆ 10:08.761385   ┆ 15:10:18.8204 ┆        ┆              ┆               │
│         ┆               ┆ UTC            ┆ 70 UTC        ┆        ┆              ┆               │
│ bronze  ┆ 1777215613422 ┆ 2026-04-26 15: ┆ 2026-04-26    ┆ C      ┆ 2            ┆ null          │
│         ┆               ┆ 00:13.422801   ┆ 15:00:25.2802 ┆        ┆              ┆               │
│         ┆               ┆ UTC            ┆ 76 UTC        ┆        ┆              ┆               │
└─────────┴───────────────┴────────────────┴───────────────┴────────┴──────────────┴───────────────┘